name:                ml
version:             0.1.0.0
github:              "neclitoris/ml"
license:             BSD-3-Clause
author:              "neclitoris"
maintainer:          "nas140301@gmail.com"
copyright:           "2025 neclitoris"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/neclitoris/ml#readme>

dependencies:
- base >= 4.7 && < 5
- blas-ffi
- deepseq
- massiv
- mtl
- netlib-ffi
- template-haskell
- vector
- haskell-src-meta
- singletons
- singletons-base
- ghc-typelits-natnormalise

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  other-modules:
  - MLambda.Foreign.Utils

benchmarks:
  ml-bench:
    main:                Bench.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ml
    - normaldistribution
    - random
    - tasty-bench

tests:
  ml-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ml
    - tasty
    - tasty-hunit
    - falsify
    - singletons
    - singletons-base

language: GHC2024
default-extensions:
- BlockArguments
- TypeFamilies
- RankNTypes
- PolyKinds
- UndecidableInstances
- NoStarIsType
